myfinance-web-netcore/Models/ErrorViewModel.cs
namespace myfinance_web_netcore.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

myfinance-web-netcore/Models/PlanoContaModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace myfinance_web_netcore.Models
{
    public class PlanoContaModel
    {   
        [Key]
        public int Id { get; set; }
        
        [Required(ErrorMessage="* Descrição do item de Plano de Conta é obrigatória!")]
	    public String Descricao { get; set; }

        [Required(ErrorMessage="* Tipo do item de Plano de Conta é obrigatório!")]
	    public String Tipo { get; set; }
    }
}

myfinance-web-netcore/Models/TransacaoModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace myfinance_web_netcore.Models
{
    public class TransacaoModel
    {
        [Key]
        public int? Id { get; set; }

        [Required(ErrorMessage = "* Histórico da Transação é obrigatório!")]
	    public String Historico { get; set; }

        [Required(ErrorMessage = "* Data da Transação é obrigatória!")]
	    public DateTime Data { get; set; }

        [Required(ErrorMessage = "* Valor da Transação é obrigatório!")]
        [Range(0.01,999999.99, ErrorMessage="* Valor deve ser maior que zero!")]
	    public decimal Valor { get; set; }

        [Required(ErrorMessage = "* Plano Conta é obrigatório!")]
        public int PlanoContaId {get; set;} 
	    
        public PlanoContaModel? ItemPlanoConta { get; set; }

        public IEnumerable<SelectListItem>? PlanoContas {get; set; }
    }
}

myfinance-web-netcore/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using myfinance_web_netcore.Models;

namespace myfinance_web_netcore.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

myfinance-web-netcore/Controllers/PlanoContaController.cs
using System.Diagnostics;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using myfinance_web_netcore.Mappers;
using myfinance_web_netcore.Models;
using myfinance_web_netcore.Services;

namespace myfinance_web_netcore.Controllers;

[Route("[controller]")]
public class PlanoContaController : Controller
{
    private readonly ILogger<PlanoContaController> _logger;
    private readonly IPlanoContaService _planoContaService;

    public PlanoContaController(ILogger<PlanoContaController> logger, IPlanoContaService planoContaService)
    {
        _logger = logger;
        _planoContaService = planoContaService;
    }

    public IActionResult Index()
    {        
        var lista = _planoContaService.Listar();
        ViewBag.ListaPlanoConta = lista;
        return View();
    }

    [HttpGet]
    [Route("Cadastro")]
    [Route("Cadastro/{id}")]
    public IActionResult Cadastro(int? id){
        if(id != null){
            var registro = _planoContaService.Consultar((int)id);
            return View(registro);
        }
        return View();
    }

    [HttpPost]
    [Route("Cadastro")]
    [Route("Cadastro/{id}")]
    public IActionResult Cadastro(PlanoContaModel model, int? id){
        _planoContaService.Salvar(model);
        return View();
    }

    [HttpGet]
    [Route("Excluir/{id}")]
    public IActionResult Excluir(int id){
        _planoContaService.Excluir(id);
        return RedirectToAction("Index");
    }
}

myfinance-web-netcore/Controllers/TransacaoController.cs
using System.Diagnostics;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using myfinance_web_netcore.Mappers;
using myfinance_web_netcore.Models;
using myfinance_web_netcore.Services;

namespace myfinance_web_netcore.Controllers;

[Route("[controller]")]
public class TransacaoController : Controller
{
    private readonly ILogger<TransacaoController> _logger;
    private readonly ITransacaoService _transacaoService;
    private readonly IPlanoContaService _planoContaService;

    public TransacaoController(ILogger<TransacaoController> logger, ITransacaoService transacaoService, IPlanoContaService planoContaService)
    {
        _logger = logger;
        _transacaoService = transacaoService;
        _planoContaService = planoContaService;
    }

    public IActionResult Index()
    {        
        var lista = _transacaoService.Listar();
        ViewBag.ListaTransacao = lista;
        return View();
    }

    [HttpPost]
    [Route("Cadastro")]
    [Route("Cadastro/{id}")]
    public IActionResult Cadastro(TransacaoModel model, int? id){
        
        if(ModelState.IsValid) 
        {
            _transacaoService.Salvar(model);
            return RedirectToAction("Cadastro");
        } 
        else {
            var listaPlanoContas = _planoContaService.Listar();
            var selectListPlanoContas = new SelectList(listaPlanoContas, "Id", "Descricao");
            model.PlanoContas = selectListPlanoContas;
            return View(model);
        }        
    }

    [HttpGet]    
    [Route("Cadastro")]
    [Route("Cadastro/{id}")]
    public IActionResult Cadastro(int? id){
        
        var listaPlanoContas = _planoContaService.Listar();
        var selectListPlanoContas = new SelectList(listaPlanoContas, "Id", "Descricao");
        

        if(id !=null){            
            var model = _transacaoService.Consultar((int)id);
            model.PlanoContas = selectListPlanoContas;
            return View(model);
        } 
        else 
        {
            var model = new TransacaoModel();
            model.PlanoContas = selectListPlanoContas;
            return View(model);
        }
    }

    [HttpGet]
    [Route("Excluir/{id}")]
    public IActionResult Excluir(int id){
        _transacaoService.Excluir(id);
        return RedirectToAction("Index");
    }
}

myfinance-web-netcore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

myfinance-web-netcore/Views/PlanoConta/Cadastro.cshtml
@model PlanoContaModel

@{
    ViewData["Title"] = "Cadastro de Plano Conta";
}

<h1>@ViewData["Title"]</h1>

<form asp-controller="PlanoConta" asp-action="Cadastro" method="post">
    <div class="container">
        <div class="mb-3">
            <label class="form-label">Descrição</label>
            <input type="hidden" id="txtId" class="form-control" asp-for="Id"/>
            <input type="text" id="txtNome" class="form-control" asp-for="Descricao"/>
            <span asp-validation-for="Descricao" class="text-danger"></span>
        </div>    
    
        <div class="mb-3">
            <label>@Html.RadioButtonFor(m => m.Tipo, "D")Despesa</label>
            <label>@Html.RadioButtonFor(m => m.Tipo, "R")Receita</label>
            <span asp-validation-for="Tipo" class="text-danger"></span>
        </div>
        
        <div class="mb-3">
            <button type="submit" class="btn btn-primary btn-lg">Salvar</button>
            <button type="button" class="btn btn-secondary btn-lg" onclick="Voltar()">Cancelar</button>
        </div>
    </div>
</form>

<script>
    function Voltar() {
        window.location.href = "../PlanoConta/";
    }
</script>

myfinance-web-netcore/Views/PlanoConta/Index.cshtml
@{
    ViewData["Title"] = "Plano Conta";
}

<button type="button" class="btn btn-block btn-primary" onclick="Novo()">Criar Item de Plano de Conta</button>
<br><br>

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Descrição</th>
        <th>Tipo</th>
        <th>#</th>
        <th>#</th>
    </tr>

@{
    foreach(var item in (List<PlanoContaModel>)ViewBag.ListaPlanoConta) {
        <tr>
            <td>@item.Id</td>
            <td>@item.Descricao</td>
            <td>@item.Tipo</td>
            <td>
                <button type="button" class="btn btn-block btn-outline-warning" onclick="Atualizar(@item.Id.ToString())">Editar</button> &nbsp;
            </td>
            <td>
                <button type="button" class="btn btn-block btn-outline-danger" onclick="Excluir(@item.Id.ToString())">Excluir</button>
            </td>
        </tr>        
    }
}
</table>

<script>
    function Novo() {
        window.location.href = "../PlanoConta/Cadastro";
    }

    function Atualizar(id) {
        window.location.href = "../PlanoConta/Cadastro/" + id;
    }

    function Excluir(id) {
        window.location.href = "../PlanoConta/Excluir/" + id;
    }
</script>

myfinance-web-netcore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - myfinance_web_netcore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/myfinance_web_netcore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">myfinance_web_netcore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PlanoConta" asp-action="Index">Plano Conta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transacao" asp-action="Index">Transação</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - myfinance_web_netcore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

myfinance-web-netcore/Views/Transacao/Cadastro.cshtml
@model TransacaoModel

@{
    ViewData["Title"] = "Cadastro Transação";
}

<h1>@ViewData["Title"]</h1>

<form asp-controller="Transacao" asp-action="Cadastro" method="post">
    <div class="container">                
        <div class="mb-3">
            <label class="form-label">Data</label>
            <input type="hidden" id="txtId" class="form-control" asp-for="Id"/>
            <input type="date" id="txtData" class="form-control" asp-for="Data"/>
            <span asp-validation-for="Data" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label">Valor</label>
            <input type="text" id="txtValor" class="form-control" asp-for="Valor" step="0.01"/>
            <span asp-validation-for="Valor" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label">Item Plano Conta</label>
            @Html.DropDownListFor(m => m.PlanoContaId, Model.PlanoContas, new {@class="form-select"})
        </div>
        <div class="mb-3">
            <label class="form-label">Histórico</label>            
            <input type="text" id="txtHistorico" class="form-control" asp-for="Historico"/>
            <span asp-validation-for="Historico" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary btn-lg">Salvar</button>
            <button type="button" class="btn btn-secondary btn-lg" onclick="Voltar()">Cancelar</button>
        </div>
    </div>
</form>

<script>
    function Voltar() {
        window.location.href = "../Transacao/";
    }
</script>

myfinance-web-netcore/Views/Transacao/Index.cshtml
@{
    ViewData["Title"] = "Transação";
}

<button type="button" class="btn btn-block btn-primary" onclick="Novo()">Registrar Transação Financeira</button>
<br><br>

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Histórico</th>
        <th>Data</th>
        <th>Valor</th>
        <th>Tipo Plano Conta</th>
        <th>#</th>
        <th>#</th>
    </tr>

@{
    foreach(var item in (List<TransacaoModel>)ViewBag.ListaTransacao) {
        <tr>
            <td>@item.Id</td>
            <td>@item.Historico</td>
            <td>@item.Data</td>
            <td>@item.Valor</td>
            <td>@item.ItemPlanoConta.Tipo</td>
            <td>
                <button type="button" class="btn btn-block btn-outline-warning" onclick="Atualizar(@item.Id.ToString())">Editar</button> &nbsp;
            </td>
            <td>
                <button type="button" class="btn btn-block btn-outline-danger" onclick="Excluir(@item.Id.ToString())">Excluir</button>
            </td>
        </tr>        
    }
}
</table>

<script>
    function Novo() {
        window.location.href = "../Transacao/Cadastro";
    }

    function Atualizar(id) {
        window.location.href = "../Transacao/Cadastro/" + id;
    }

    function Excluir(id) {
        window.location.href = "../Transacao/Excluir/" + id;
    }
</script>